# -*- coding: utf-8 -*-
"""ex5_engenharia_de_contexto_e_logica_fisica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyRwW_R7CVc7EfUaiMU34rly8VubCijR
"""

print("=" * 55)

print(" DESAFIO 1 — FILTRO DE SOMBRA NO EMOJI 5x5")

print("=" * 55)

# Aqui tá a estrutura base que o professor deu.

# É um dicionário com o nome do emoji e a grade de pixels.

# Cada linha é uma lista, e cada pixel é uma tupla (R, G, B).
emoji_data = {
  "nome": "Smile",
  "grade": [
    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 0
    [(255,255,0), (0,0,0),  (255,255,0), (0,0,0),  (255,255,0)], # Linha 1 (Olhos)
    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], # Linha 2
    [(255,255,0), (0,0,0),  (0,0,0),  (0,0,0),  (255,255,0)], # Linha 3 (Boca)
    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)] # Linha 4
  ]
}
# Vou criar uma nova estrutura pra guardar o emoji depois do filtro.

# Não dá pra modificar a original direto porque tupla é imutável —

# aprendi isso do jeito difícil tentando fazer emoji_data["grade"][0][0][0] = 100.

# Python simplesmente xinga a gente. rsrs

emoji_filtrado = {

  "nome": emoji_data["nome"],
  "grade": [] # essa lista vai ser preenchida pelos loops lá embaixo

}
# Primeiro nível de loop: itera sobre o dicionário.

# .items() retorna pares (chave, valor). A gente só processa a "grade".

for chave, valor in emoji_data.items():
  if chave == "grade": # ignora a chave "nome", só quer a grade

    # Segundo nível de loop: itera sobre cada linha da grade.

    # Cada "linha" é uma lista de 5 pixels.

    for linha in valor:
      nova_linha = [] # cria uma lista vazia pra montar a linha nova

      # Terceiro nível de loop: itera sobre cada pixel da linha.

      # Aqui é onde a mágica acontece — verifica se é amarelo e aplica o filtro.

      for pixel in linha:
        if pixel == (255, 255, 0): # é amarelo?

          # Tuplas são imutáveis então não dá pra mudar no lugar.

          # A saída é criar uma nova tupla com os valores reduzidos.

          # Uso int() pra garantir que não fica float (255//2 = 127, não 127.5).

          pixel_sombra = (pixel[0] // 2, pixel[1] // 2, pixel[2] // 2)
          nova_linha.append(pixel_sombra)

        else:
          # Pixel preto (olhos/boca) fica igual — não mexe.

          nova_linha.append(pixel)

      # Adiciona a linha processada à grade do emoji filtrado.

      emoji_filtrado["grade"].append(nova_linha)

# Agora vamos imprimir os resultados lado a lado pra comparar.

print(f"\nEmoji original → '{emoji_data['nome']}'")

print(f"Emoji filtrado → '{emoji_filtrado['nome']} (Sombra)'\n")

print(" Grade ORIGINAL       →  Grade COM SOMBRA")
print(" " + "-" * 50)

for i in range(len(emoji_data["grade"])):

  original = emoji_data["grade"][i]
  filtrada = emoji_filtrado["grade"][i]

  print(f" {original}")
  print(f"               →  {filtrada}\n")

# Só pra visualizar de forma mais bonita — mostra a carinha do emoji

# usando os caracteres de bloco. Amarelo = 🟡, Preto = ⬛.

print("\n Visualização do emoji ORIGINAL:")

for linha in emoji_data["grade"]:
  row_str = ""
  for pixel in linha:
    if pixel == (255, 255, 0):
      row_str += "🟡"
    else:
      row_str += "⬛"
  print(" " + row_str)

print("\n Visualização do emoji COM SOMBRA:")

for linha in emoji_filtrado["grade"]:
  row_str = ""
  for pixel in linha:
    if pixel == (127, 127, 0): # amarelo escuro depois do filtro
      row_str += "🟤"
    else:
      row_str += "⬛"
  print(" " + row_str)
# -----------------------------------------------------------------------

# DESAFIO 2: MATRIZES MUSICAIS — TRANSPOSIÇÃO

# Aqui a ideia é pegar matrizes 2x2 de frequências musicais

# e transpor elas (linha vira coluna e coluna vira linha).

# A transposição de [[a, b], [c, d]] vira [[a, c], [b, d]].

# -----------------------------------------------------------------------

print("\n" + "=" * 55)

print(" DESAFIO 2 — TRANSPOSIÇÃO DAS MATRIZES MUSICAIS")

print("=" * 55)

# Estrutura base fornecida pelo professor.

# "Toques" é uma lista de dicionários, onde cada dicionário tem

# o nome da música como chave e uma tupla de listas como valor.

biblioteca_musical = {
  "Toques": [
    {"Alegre": ([440, 480], [520, 560])},
    {"Triste": ([200, 150], [100, 50])}
  ]
}

# Vou guardar as matrizes transpostas numa estrutura nova,

# porque mexer no original enquanto itera é receita pra bug.

biblioteca_transposta = {"Toques": []}

print("\nMatrizes ORIGINAIS e suas TRANSPOSIÇÕES:\n")

# Primeiro nível: itera sobre a lista de "Toques".

# Cada item dessa lista é um dicionário com uma música.

for musica_dict in biblioteca_musical["Toques"]:

  novo_dict = {} # vai guardar a versão transposta dessa música

  # Segundo nível: itera sobre os itens do dicionário da música.

  # .items() devolve (nome_musica, (linha0, linha1)).

  for nome, matriz in musica_dict.items():
    print(f" 🎵 Música: {nome}")
    print(f"  Original : {list(matriz)}")

    # Aqui começo a montar a matriz transposta.

    # Pra uma matriz 2x2, a transposição funciona assim:

    # transposta[0] = [matriz[0][0], matriz[1][0]]

    # transposta[1] = [matriz[0][1], matriz[1][1]]

    # Em outras palavras: transposta[coluna][linha] = original[linha][coluna]

    num_linhas = len(matriz)
    num_colunas = len(matriz[0])
    transposta = []

    # Terceiro nível: monta cada linha da transposta.

    # Cada "linha da transposta" é na verdade uma coluna do original.

    for col in range(num_colunas):
      nova_linha = []
      for linha in range(num_linhas):

        # Aqui pega o elemento na posição (linha, col) do original

        # e joga na posição (col, linha) da transposta.

        nova_linha.append(matriz[linha][col])
      transposta.append(nova_linha)

    print(f"  Transposta : {transposta}\n")

    # Atualiza o dicionário com a nova matriz usando .update().

    # O .update() substitui o valor da chave se já existir,

    # ou adiciona um novo par chave-valor se não existir.

    # Aqui uso pra colocar a matriz transposta no lugar da original.

    novo_dict.update({nome: transposta})

  biblioteca_transposta["Toques"].append(novo_dict)

print(" Estrutura transposta completa:")
print(f" {biblioteca_transposta}")





# -----------------------------------------------------------------------

# DESAFIO 3: O INTEGRADOR — PLAYLIST DE IMAGENS

# Aqui a missão é criar uma estrutura que mistura tudo:

# dicionário, lista e tupla juntos.

# Uso 3 níveis de for e pelo menos um método de cada estrutura.

# Métodos usados: .pop() (lista), .keys() (dict), .insert() (lista)

# -----------------------------------------------------------------------



print("\n" + "=" * 55)
print(" DESAFIO 3 — PLAYLIST DE IMAGENS (INTEGRADOR)")
print("=" * 55)

# A estrutura: um dicionário chamado "playlist" que contém:

# - "titulo" (string): nome da playlist

# - "frames" (lista): lista de frames/cenas da animação

# - Cada frame é um dicionário com "id", "duracao" (tupla) e "pixels" (lista de tuplas)

playlist = {
  "titulo": "Animação Emoji Pisca",
  "frames": [
    {
      "id": 1,
      "duracao": (0, 500), # tupla (inicio_ms, fim_ms)
      "pixels": [
        (255, 255, 0), # pixel 0 — rosto amarelo
        (0, 0, 0),   # pixel 1 — olho esquerdo (aberto)
        (255, 255, 0), # pixel 2 — nariz
        (0, 0, 0),   # pixel 3 — olho direito (aberto)
        (255, 255, 0)  # pixel 4 — boca
      ]
    },
    {
      "id": 2,
      "duracao": (500, 1000),
      "pixels": [
        (255, 255, 0), # pixel 0 — rosto amarelo
        (255, 255, 0), # pixel 1 — olho esquerdo (fechado = amarelo)
        (255, 255, 0), # pixel 2 — nariz
        (255, 255, 0), # pixel 3 — olho direito (fechado = amarelo)
        (255, 255, 0)  # pixel 4 — boca
      ]
    },
    {
      "id": 3,
      "duracao": (1000, 1500),
      "pixels": [
        (255, 255, 0),
        (0, 0, 0),
        (255, 255, 0),
        (0, 0, 0),
        (255, 255, 0)
      ]
    }
  ]
}
print(f"\n Playlist: '{playlist['titulo']}'")
print(f" Total de frames: {len(playlist['frames'])}\n")



# OPERAÇÃO 1: .insert() — Adiciona um frame especial no início da playlist.

# .insert(índice, valor) coloca o elemento na posição especificada

# e empurra tudo que estava lá pra frente.

frame_intro = {
  "id": 0,
  "duracao": (0, 200), # tupla: frame curtinho de introdução
  "pixels": [(128, 128, 0)] * 5 # tudo meio apagado — fade in

}
playlist["frames"].insert(0, frame_intro) # .insert() → método de lista
print(" [INSERT] Frame de introdução adicionado no índice 0.")

# OPERAÇÃO 2: .pop() — Remove o último frame (o repete era desnecessário).

# .pop() sem argumento remove e retorna o último elemento da lista.

removido = playlist["frames"].pop() # .pop() → método de lista
print(f" [POP] Frame id={removido['id']} removido do final da playlist.")

# Agora vamos percorrer a estrutura completa com 3 níveis de for

# e calcular a duração total da animação no processo.

print(f"\n Frames da playlist '{playlist['titulo']}':\n")

duracao_total_ms = 0

# Nível 1: itera sobre as chaves do dicionário playlist usando .keys()

for chave in playlist.keys(): # .keys() → método de dicionário
  if chave == "frames":
    # Nível 2: itera sobre cada frame (que é um dicionário) da lista.

    for frame in playlist[chave]:
      inicio, fim = frame["duracao"] # desempacota a tupla de duração
      duracao_frame = fim - inicio
      duracao_total_ms += duracao_frame

      print(f" Frame #{frame['id']} | Duração: {inicio}ms → {fim}ms ({duracao_frame}ms)")
      print(f"  Pixels:", end=" ")

      # Nível 3: itera sobre cada pixel (tupla RGB) dentro do frame.

      # Aqui checa se o pixel é amarelo ou preto e imprime um símbolo.

      for pixel in frame["pixels"]:
        r, g, b = pixel # desempacota a tupla
        if r > 0 and g > 0:
          print("🟡", end="")
        else:
          print("⬛", end="")
      print() # quebra de linha depois dos pixels

print(f"\n ✅ Duração total da animação: {duracao_total_ms}ms ({duracao_total_ms/1000:.1f}s)")
print(f" ✅ Total de frames na playlist final: {len(playlist['frames'])}")


print("\n" + "=" * 55)
print(" RESUMO DO PROJETO")
print("=" * 55)
print("""

 Desafio 1 — Filtro de Sombra:

  • 3 níveis de for (dict → linhas → pixels)
  • .items() pra iterar o dicionário
  • .append() pra montar as linhas novas
  • Nova tupla criada pra cada pixel amarelo (imutabilidade!)

 Desafio 2 — Transposição Musical:

  • 3 níveis de for (lista → dict → células da matriz)
  • .items() pra acessar nome e matriz
  • .update() pra atualizar o dicionário com a transposta

 Desafio 3 — Playlist Integrada:

  • Estrutura com dict + lista + tupla
  • .insert(0, frame_intro) → adiciona no início da lista
  • .pop() → remove o último frame
  • .keys() → itera as chaves do dicionário principal
  • 3 níveis de for (chaves → frames → pixels)

""")